# Numbers in Julia

In [3]:
a = 10
@show typeof(a)

typeof(a) = Int64


Int64

In [4]:
b = 10.2
@show typeof(b)

typeof(b) = Float64


Float64

In [5]:
set_bigfloat_precision(128)
c = BigFloat(2.1)
@show c
@show typeof(c)

c = 2.100000000000000088817841970012523233891
typeof(c) = BigFloat


BigFloat

In [6]:
set_bigfloat_precision(256)
d = BigFloat(2.1)
@show d
@show typeof(d)

d = 2.100000000000000088817841970012523233890533447265625000000000000000000000000000
typeof(d) = BigFloat


BigFloat

In [7]:
v = zeros(5)
@show v
@show typeof(v)

v = [0.0,0.0,0.0,0.0,0.0]
typeof(v) = Array{Float64,1}


Array{Float64,1}

In [10]:
w = zeros(Int64,5)
@show w
@show typeof(w)

w = [0,0,0,0,0]
typeof(w) = Array{Int64,1}


Array{Int64,1}

In [11]:
w = w + 2.5

5-element Array{Float64,1}:
 2.5
 2.5
 2.5
 2.5
 2.5

In [12]:
WORD_SIZE

64

In [13]:
typemax(Int64)

9223372036854775807

In [18]:
# let's double check that 2^{WORD_SIZE - 1} - 1 is equal to typemax(Int64)
2^(WORD_SIZE-1) - 1

9223372036854775807

In [19]:
typemax(Float64)

Inf

In [20]:
typeof(Inf)

Float64

# Greek letters are always fun

In [75]:
λ = 7
α = 10
β = 20
α + β

30

# Vectors and Matrices

In [52]:
# this is a 5 by 5 matrix of all ones and type Float64
w1 = ones(5,5)

5x5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [25]:
# this is a 5 by 1 matrix of all ones and type Float64
w2 = ones(5,1)

5x1 Array{Float64,2}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
# this is a 1 by 5 matrix of all ones and type Float64
w3 = ones(1,5)

1x5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0

In [28]:
# this will generate an error - dot product is only defined on vectors
dot(w2,w2)

LoadError: LoadError: MethodError: `dot` has no method matching dot(::Array{Float64,2}, ::Array{Float64,2})
while loading In[28], in expression starting on line 1

In [30]:
# let's try this:
w2 = ones(Int64,5)

5-element Array{Int64,1}:
 1
 1
 1
 1
 1

In [31]:
dot(w2,w2)

5

In [32]:
w4 = w2'

1x5 Array{Int64,2}:
 1  1  1  1  1

In [41]:
w5 = w4'

5x1 Array{Int64,2}:
 1
 1
 1
 1
 1

In [42]:
# that's bad, we want it to stay a column vector
w5 = vec(w5)

5-element Array{Int64,1}:
 1
 1
 1
 1
 1

In [43]:
# this will generate an error
w5[2] = 1.3

LoadError: LoadError: InexactError()
while loading In[43], in expression starting on line 2

In [46]:
@show w5

w5 = [2,2,2,2,2]


5-element Array{Int64,1}:
 2
 2
 2
 2
 2

In [47]:
w5[:] = 2.2

LoadError: LoadError: InexactError()
while loading In[47], in expression starting on line 1

In [49]:
w5 = 2
@show w5

w5 = 2


2

# Syntax

In [54]:
# access elements in a vector or matrix
w1[1,1]

1.0

In [55]:
# for loops
total_sum = 0
for i = 1:10
    total_sum += i
end
@show total_sum

total_sum = 55


55

In [57]:
# for loops
input_vals = ["this","is","a","workshop"]
for x in input_vals
    println("$x")
end

this
is
a
workshop


In [64]:
# if statements
my_rand = rand()
if my_rand > 0.5
    println("I win")
else
    println("You win")
end

You win


In [72]:
# while loops
my_rand = rand()
ref = 0.5
win_in_a_row = 0
while my_rand > ref
    my_rand = rand()
    win_in_a_row += 1
end
println("I won $win_in_a_row times")


I won 2 times


# Strings

In [79]:
my_first_string = "This is a string."

"This is a string."

In [76]:
my_second_string = "This is a string as well"

"This is a string as well"

In [82]:
my_first_string*" "*my_second_string

"This is a string. This is a string as well"

In [84]:
# this will generate an error
val = 1
my_first_string*val

LoadError: LoadError: MethodError: `*` has no method matching *(::ASCIIString, ::Int64)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
  *{T<:Number}(!Matched::Bool, ::T<:Number)
  *(!Matched::Complex{Bool}, ::Real)
  ...
while loading In[84], in expression starting on line 3

In [85]:
val = 1
join([my_first_string,val])

"This is a string.1"