In [13]:
function hello(ARGS)
    for x in ARGS
        println("Hello ", x, ", how are you doing today?")
    end
end

hello (generic function with 2 methods)

In [16]:
hello(["name1","name2"])

Hello name1, how are you doing today?
Hello name2, how are you doing today?


In [22]:
A = 1:9
A = reshape(A,3,3)'
B = 0:-1:-8
B = reshape(B,3,3)
M = A*B;

In [20]:
# this will generate an error
x = ones(1000,1);
y = 1:1000;
x_dot_y = x'*y;
println(x_dot_y);

LoadError: LoadError: MethodError: `A_mul_B!` has no method matching A_mul_B!(::Array{Float64,1}, ::Array{Float64,2}, ::UnitRange{Int64})
Closest candidates are:
  A_mul_B!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},1},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},1},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, !Matched::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},1},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  A_mul_B!(::Union{DenseArray{T,1},SubArray{T,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{T,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, !Matched::Union{DenseArray{T,1},SubArray{T,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  A_mul_B!(::Union{AbstractArray{T,1},AbstractArray{T,2}}, !Matched::Tridiagonal{T}, ::Union{AbstractArray{T,1},AbstractArray{T,2}})
  ...
while loading In[20], in expression starting on line 3

In [21]:
x = ones(1000,1);
y = collect(1:1000);
x_dot_y = x'*y;
println(x_dot_y);

[500500.0]


In [23]:
x = [5 3 -1]';
e = ones(3,1);
exT = e*x';
xeT = x*e';
println(xeT);

[5.0 5.0 5.0
 3.0 3.0 3.0
 -1.0 -1.0 -1.0]


In [24]:
x = [1 2 3]'
e1 = [1 0 0]'
e3 = [0 0 1]'
e1xT = e1*x';
xe3T = x*e3'
println(xe3T);

[0 0 1
 0 0 2
 0 0 3]


In [25]:
A = rand(5,5)

5x5 Array{Float64,2}:
 0.53352     0.624571   0.957504   0.386542  0.908649 
 0.00809016  0.863282   0.0395534  0.591512  0.164629 
 0.710279    0.0470675  0.523217   0.90947   0.0623155
 0.137988    0.690597   0.196376   0.984792  0.904705 
 0.470293    0.768976   0.819062   0.836116  0.960817 

In [28]:
svd(A)

(
5x5 Array{Float64,2}:
 -0.501356   0.317916    0.56502   -0.2335      0.523261 
 -0.271049  -0.582134   -0.286618  -0.705434    0.0886818
 -0.321123   0.583598   -0.735964  -0.0450634   0.112335 
 -0.475806  -0.465226   -0.157234   0.667634    0.294475 
 -0.587931   0.0550217   0.179545   0.0086411  -0.786765 ,

[2.9846788650810074,0.9608446715631855,0.8353865296987807,0.44647036610759766,0.041056698986964575],
5x5 Array{Float64,2}:
 -0.28141    0.563153  -0.192566  -0.148055   0.738014
 -0.449943  -0.578127   0.120067  -0.647828   0.170948
 -0.41337    0.562459   0.312172  -0.306565  -0.566861
 -0.53819   -0.107024  -0.74839    0.260244  -0.266614
 -0.507776  -0.144271   0.539411   0.629832   0.183567)

In [29]:
lu(A)

(
5x5 Array{Float64,2}:
 1.0        0.0       0.0       0.0       0.0
 0.0113901  1.0       0.0       0.0       0.0
 0.751141   0.682955  1.0       0.0       0.0
 0.194273   0.789866  0.125924  1.0       0.0
 0.662125   0.85519   0.819679  0.699776  1.0,

5x5 Array{Float64,2}:
 0.710279  0.0470675  0.523217    0.90947    0.0623155
 0.0       0.862746   0.0335939   0.581153   0.163919 
 0.0       0.0        0.541551   -0.6935     0.749892 
 0.0       0.0        0.0         0.436403   0.668695 
 0.0       0.0        0.0         0.0       -0.303233 ,

[3,2,1,4,5])

In [30]:
chol(A)

LoadError: LoadError: Base.LinAlg.PosDefException(3)
while loading In[30], in expression starting on line 1

In [31]:
qr(A)

(
5x5 Array{Float64,2}:
 -0.52584     -0.156637   0.563142   0.350082   -0.509185 
 -0.00797372  -0.691365  -0.427519   0.565991    0.13723  
 -0.700055     0.424469  -0.569103   0.0752038   0.0146734
 -0.136002    -0.467441  -0.282171  -0.667946   -0.487063 
 -0.463524    -0.314331   0.310804  -0.324483    0.696027 ,

5x5 Array{Float64,2}:
 -1.0146  -0.818619  -1.27645   -1.36615   -1.09114 
  0.0     -1.23922   -0.304488  -0.806606  -0.954607
  0.0      0.0        0.423693  -0.570799   0.449196
  0.0      0.0        0.0       -0.390585  -0.500095
  0.0      0.0        0.0        0.0       -0.211058)