In [2]:
v = zeros(Int64,5)

5-element Array{Int64,1}:
 0
 0
 0
 0
 0

In [3]:
v[6] = 7

LoadError: LoadError: BoundsError: attempt to access 5-element Array{Int64,1}:
 0
 0
 0
 0
 0
  at index [6]
while loading In[3], in expression starting on line 1

In [5]:
for i = 1:5
    head = 10;
end
head

LoadError: LoadError: UndefVarError: head not defined
while loading In[5], in expression starting on line 4

In [6]:
h = 1
if 1
    h += 1
end

LoadError: LoadError: TypeError: non-boolean (Int64) used in boolean context
while loading In[6], in expression starting on line 2

In [7]:
2^2

4

In [8]:
2^-1

LoadError: LoadError: DomainError:
Cannot raise an integer x to a negative power -n. 
Make x a float by adding a zero decimal (e.g. 2.0^-n instead of 2^-n), or write 1/x^n, float(x)^-n, or (x//1)^-n.
while loading In[8], in expression starting on line 1

In [9]:
2.0^-1

0.5

In [10]:
A = sprand(5,5,0.1)

5x5 sparse matrix with 2 Float64 entries:
	[2, 2]  =  0.512652
	[3, 3]  =  0.118195

In [11]:
B = sprand(5,5,0.1)

5x5 sparse matrix with 1 Float64 entries:
	[5, 4]  =  0.82197

In [15]:
C = maximum(A)

0.5126521701034492

In [16]:
D = max(A)

LoadError: LoadError: MethodError: `max` has no method matching max(::SparseMatrixCSC{Float64,Int64})
Closest candidates are:
  max{T1<:Real,T2<:Real}(::AbstractArray{T1<:Real,N}, !Matched::T2<:Real)
  max{Tv1,Ti1,Tv2,Ti2}(::SparseMatrixCSC{Tv1,Ti1}, !Matched::SparseMatrixCSC{Tv2,Ti2})
  max{T1<:Real,T2<:Real}(::AbstractArray{T1<:Real,N}, !Matched::AbstractArray{T2<:Real,N})
  ...
while loading In[16], in expression starting on line 1

In [21]:
E = max(A,B)

5x5 sparse matrix with 3 Float64 entries:
	[2, 2]  =  0.512652
	[3, 3]  =  0.118195
	[5, 4]  =  0.82197

In [17]:
x = collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [18]:
y = x

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [19]:
y[3] = 100

100

In [20]:
x

5-element Array{Int64,1}:
   1
   2
 100
   4
   5